---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 10.22.0.15
      username: administrator@vsphere.local
      password: password
      validate_certs: False
      name: testvm
      template: Debian-Template-PJ
      datacenter: Datacenter
      folder: /10.22.54.0_PJ
      state: poweredon
      wait_for_ip_address: no
